### ISSUE TITLE
Fluentd log level field

### ISSUE THREAD

**Issue by tianctrl** [inovex/kubernetes-logging#1]
I read your blog, and a picture in your article that show kibana table. There is a "level" field.
Could you tell me how to add the "level" field?
My fluentd and es did not have this field.

**Comment by hikhvar** [comment]
Hello, the picture is taken from a log line of the structured logging application. It is actually added by the application. So one log line of the application looks like the line below. That field `level` in the JSON is the field you see in the screenshot. The field `log` in the screenshot is the raw log line the application writes to STDOUT. 

```
{"level":"info","Textlen":599,"words":100,"prefix":2,"msg":"In previous blog articles we talked about the basic Redis features and learned how to persist, backup and restore your dataset in cause of a distributed system. That means your Sentinel processes are a part of a distributed system. That means clients can connect to the Sentinel processes. On each of your Redis Master and two Slaves before setting up the Sentinel which Redis master it should monitor. In short, these are the benefits of using Sentinel: Monitoring: Sentinel constantly checks if the Redis setup will be informed about the basic Redis features and learned how to persist, backup and","time":"2016-12-23T09:08:35Z"}
```

We tell the fluentd in the configuration of the event source that each line in the log files will be a complete JSON object. 
```
<source>
....
  path /var/log/containers/*.log
....
  format json
....
</source>
```
Therefore the fluentd parses the line and adds the field `level` from the logline to the elasticsearch document.

**Comment by tianctrl** [comment]
Oh, I see.  Thank you :)
I just want to add a field like your "level" , so I can have the log level.
And when I use elasticsearch for query logs, I can see the log level in every index.
Do you know how to config fluentd , please?

**Comment by hikhvar** [comment]
What is your source of the log events? Kubernetes Pods like in this demo? Do you have any source of truth for the log level?

**Comment by tianctrl** [comment]
I have a k8s cluster, and deploy efk. I am a  newcomer. 
When I use curl command query logs, I want to the logs could have a log level field.
I don't know my thoughts is right or not? 
I think fluentd maybe can do this. But I don't find out any idea.

**Comment by hikhvar** [comment]
The log level should be encoded some where in your log line. Than you can use regular expressions to parse your log lines and extract that information. A introduction can be found in the official [fluentd documentation](http://docs.fluentd.org/v0.12/articles/common-log-formats). [This editor](http://fluentular.herokuapp.com/) helps you to debug your regular expressions.

**Comment by tianctrl** [comment]
Thank you for your help, you are very kind.
I'm going to read the official document again.

**Comment by hikhvar** [comment]
Ok, I will close that issue now.
