### ISSUE TITLE
DaemonSet fluentd-logging can't read container logs - Minikube

### ISSUE THREAD

**Issue by robzenn92** [inovex/kubernetes-logging#2]
# Versions

Hi !
I am running Minikube version: v0.22.3

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-09-29T05:56:06Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
```
```
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

# What I have done

I executed `run_demo.sh` and everything was deployed (pods were  running and configmap ok). :ok_hand:

# What happened

However, I was't able to see logs onto Kibana.

When I execute the command `kubectl --namespace kube-system logs -f fluentd-logging-z6lcd` I get the following (one line for each container):

```
...
2017-10-23 19:30:16 +0000 [warn]: /var/log/containers/<container>.log unreadable. It is excluded and would be examined next time.
...
```

After googling a bit, I found out that the same issue was faced in other fluentd images (e.g. [https://github.com/fabric8io/docker-fluentd-kubernetes/issues/14](https://github.com/fabric8io/docker-fluentd-kubernetes/issues/14)). 

So I compared your [fluentd-daemonset.yaml](https://github.com/inovex/kubernetes-logging/blob/master/kubernetes_config/fluentd-daemonset.yaml) with the solution proposed [here](https://github.com/fabric8io/docker-fluentd-kubernetes/issues/14#issuecomment-246594243).

It turns out that your `fluentd-daemonset.yaml` definition missed an entry in [volumeMounts](https://github.com/inovex/kubernetes-logging/blob/master/kubernetes_config/fluentd-daemonset.yaml#L31). In particular the following:

```
        volumeMounts:
        ...
        - name: var-lib-docker
          mountPath: /var/lib/docker/
          readOnly: true
        ...
```

And then in [volumes](https://github.com/inovex/kubernetes-logging/blob/master/kubernetes_config/fluentd-daemonset.yaml#L49):

```
      terminationGracePeriodSeconds: 30
      volumes:
      ...
      - name: var-lib-docker
        hostPath:
          path: /var/lib/docker/
```

Once I have added them and re-deploy the DaemonSet I got the following (as expected):

```
...
2017-10-23 19:20:07 +0000 [info]: following tail of /var/log/containers/<container>.log
...
```

And now I am able to see logs onto Kibana. Hope it helps. 😃 
PS: Let me know if you want a PR.

**Comment by hikhvar** [comment]
Thanks for the hint! I added the missing mount in this commit: 1ffe7b9ec0506a9675a0ed0dcbf8d43ed3302f1f

It worked for me. Can you verify it?

**Comment by robzenn92** [comment]
@hikhvar verified! It worked! You can close the issue! 😃 
Thanks a lot!

**Comment by hikhvar** [comment]
Ok. Solved.
